# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(max_length=2)),
                ('anoPeriodo', models.CharField(max_length=4)),
                ('diaIniciaPeriodo', models.CharField(max_length=2)),
                ('diaFinPeriodo', models.CharField(max_length=2)),
                ('fechaEjecucion', models.DateTimeField(verbose_name='Fecha de ejecucion')),
            ],
        ),
        migrations.CreateModel(
            name='MesesReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='ejecucionreporte',
            name='mesPeriodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportesVC.MesReporte'),
        ),
        migrations.AddField(
            model_name='ejecucionreporte',
            name='tipoReporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportesVC.TipoReporte'),
        ),
    ]
