# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportesVC', '0002_auto_20170403_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariablesUltimoReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('valor', models.CharField(max_length=50)),
            ],
        ),
    ]
