# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportesVC', '0003_variablesultimoreporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucionreporte',
            name='estatus',
            field=models.CharField(default='creacion', max_length=10),
        ),
        migrations.AddField(
            model_name='ejecucionreporte',
            name='nombreArchivo',
            field=models.CharField(default='creacion', max_length=50),
        ),
        migrations.AddField(
            model_name='ejecucionreporte',
            name='nombreZip',
            field=models.CharField(default='creacion', max_length=50),
        ),
        migrations.AddField(
            model_name='ejecucionreporte',
            name='rutaArchivo',
            field=models.CharField(default='creacion', max_length=50),
        ),
    ]
