# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportesVC', '0007_auto_20170503_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporeporte',
            name='nombreLargo',
            field=models.CharField(default='', max_length=20),
        ),
    ]
