# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportesVC', '0009_auto_20170704_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejecucionreporte',
            options={},
        ),
    ]
