# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportesVC', '0010_auto_20170704_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejecucionreporte',
            options={'permissions': (('can_run_Conciliacion', 'Ejecuta Conciliacion'),)},
        ),
    ]
