# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportesVC', '0011_auto_20170704_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejecucionreporte',
            options={'permissions': (('can_run_Report', 'Ejecuta Reporte'), ('can_run_Calculos', 'Ejecuta Calculos'), ('can_run_Conciliacion', 'Ejecuta Conciliacion'))},
        ),
    ]
