# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-15 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportesVC', '0014_actualizacionesarchivos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejecucionreporte',
            options={'permissions': (('can_run_Report', 'Ejecuta Reporte'), ('can_run_Calculos', 'Ejecuta Calculos'), ('can_run_Conciliacion', 'Ejecuta Conciliacion'), ('can_run_AdminConta', 'Administracion Conta'))},
        ),
        migrations.AlterField(
            model_name='actualizacionesarchivos',
            name='fechaEjecucion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ejecucion'),
        ),
    ]
